---
services:
  db:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      #MARIADB_ROOT_PASSWORD: password
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: APP_RISTORANTI
    volumes:
      - mariadb:/var/lib/mysql:rw
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro

volumes:
  mariadb: {}
